repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.21.1
    hooks:
      - id: gitleaks
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.9
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format
- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.1
  hooks:
    - id: golangci-lint
      args: ['--config', '.github/.golangci.yml', 'src/...']
