metadata:
  product_id: REST_Trigger_product
  version_tag: v1.0.0
  workflow_name: REST_Trigger_workflow
  workflow_type: data
  process_name: REST_Trigger_process
  process_type: trigger

nats:
  url: 'nats://localhost:4222'
  stream: trigger
  output: rest-trigger-output

minio:
  internal_folder: ".kai"
  endpoint: "localhost:9000"
  access_key_id: minioadmin
  access_key_secret: minioadmin
  use_ssl: false
  bucket: test-bucket

auth:
  endpoint: "http://auth.kai.local"
  client: "kai"
  client_secret: "kai_pwd"
  realm: "konstellation"

predictions:
  endpoint: localhost:6379
  username: default
  password: redispw
  index: predictionsIdx

model_registry:
  folder_name: ".models"

measurements:
  endpoint: "localhost:4317"
  insecure: true
  timeout: 5
  metrics_interval: 10

centralized_configuration:
  global:
    bucket: global
  product:
    bucket: product
  workflow:
    bucket: workflow
  process:
    bucket: process
