name: "Linter"

on:
  pull_request:
    branches:
      - main

jobs:
  quality-checks:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read
      checks: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.2

      - name: API Go Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.62.2
          working-directory: ./src
          args: --config ../../.github/.golangci.yml
          github-token: ${{ secrets.GITHUB_TOKEN }}